modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="CC0-1.0"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="simplebuilding"
description='''
SimpleBuilding (Forge scaffold).
'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
