plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}
apply from: rootProject.file('gradle/module-neoforge.gradle')

neoForge.runs {
    moduleIntegrationGameTest {
        type = 'gameTestServer'
        gameDirectory = rootProject.layout.projectDirectory.dir('integration/run-neoforge-263')
        programArguments.addAll '--tests', (project.findProperty('gametestFilter') ?: '__MODID__:*').toString(), '--report', layout.buildDirectory.file('module-junit.xml').get().asFile.absolutePath
    }
}
