modLoader="javafml"
loaderVersion="[66,)"
license="CC0-1.0"
[[mods]]
modId="simplemoney"
version="${version}"
displayName="Simple Money"
[[dependencies.simplemoney]]
modId="forge"
mandatory=true
versionRange="[66,)"
ordering="AFTER"
side="BOTH"
[[dependencies.simplemoney]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simplemoney]]
modId="modmenu"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simplemoney]]
modId="simplebuilding"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplefun"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplemodels"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplequalityoflife"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simpleriding"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplesounds"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simpletweaks"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplevisuals"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="wiringexample"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
