modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simpledimension"
version="${version}"
displayName="Simple Dimensions"
[[dependencies.simpledimension]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"

[[mixins]]
config="simpledimension.mixins.json"

[[dependencies.simpledimension]]
modId="cloth_config"
type="required"
versionRange="[0,)"

[[dependencies.simpledimension]]
modId="simplebuilding"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="modmenu"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simpledimension]]
modId="flan"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="ftbchunks"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="openpartiesandclaims"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="griefdefender"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="claimchunk"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
