package com.simplebuilding.modules.simpletweaks.mixin.claims;
import com.simplebuilding.modules.simpletweaks.claims.Claims;
import net.minecraft.core.*;
import net.minecraft.server.level.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.state.BlockState;
import org.spongepowered.asm.mixin.*;
import org.spongepowered.asm.mixin.injection.*;
import org.spongepowered.asm.mixin.injection.callback.*;
/** Mutable Vanilla world-entity hurtServer overrides, including final methods, in pinned 26.3 sources. */
@Mixin(targets={"net.minecraft.world.entity.ExperienceOrb","net.minecraft.world.entity.boss.enderdragon.EndCrystal","net.minecraft.world.entity.boss.enderdragon.EnderDragonPart","net.minecraft.world.entity.item.FallingBlockEntity","net.minecraft.world.entity.item.ItemEntity","net.minecraft.world.entity.LivingEntity","net.minecraft.world.entity.ambient.Bat","net.minecraft.world.entity.animal.allay.Allay","net.minecraft.world.entity.animal.armadillo.Armadillo","net.minecraft.world.entity.animal.axolotl.Axolotl","net.minecraft.world.entity.animal.bee.Bee","net.minecraft.world.entity.animal.equine.AbstractHorse","net.minecraft.world.entity.animal.golem.IronGolem","net.minecraft.world.entity.animal.nautilus.AbstractNautilus","net.minecraft.world.entity.animal.panda.Panda","net.minecraft.world.entity.animal.parrot.Parrot","net.minecraft.world.entity.animal.squid.GlowSquid","net.minecraft.world.entity.animal.squid.Squid","net.minecraft.world.entity.animal.wolf.Wolf","net.minecraft.world.entity.boss.enderdragon.EnderDragon","net.minecraft.world.entity.boss.wither.WitherBoss","net.minecraft.world.entity.decoration.ArmorStand","net.minecraft.world.entity.decoration.BlockAttachedEntity","net.minecraft.world.entity.decoration.Cushion","net.minecraft.world.entity.decoration.ItemFrame","net.minecraft.world.entity.monster.Enderman","net.minecraft.world.entity.monster.Ghast","net.minecraft.world.entity.monster.Guardian","net.minecraft.world.entity.monster.Shulker","net.minecraft.world.entity.monster.Silverfish","net.minecraft.world.entity.monster.Zoglin","net.minecraft.world.entity.monster.creaking.Creaking","net.minecraft.world.entity.monster.cubemob.SulfurCube","net.minecraft.world.entity.monster.hoglin.Hoglin","net.minecraft.world.entity.monster.piglin.Piglin","net.minecraft.world.entity.monster.piglin.PiglinBrute","net.minecraft.world.entity.monster.warden.Warden","net.minecraft.world.entity.monster.zombie.Zombie","net.minecraft.world.entity.player.Player","net.minecraft.world.entity.projectile.EvokerFangs","net.minecraft.world.entity.projectile.EyeOfEnder","net.minecraft.world.entity.projectile.Projectile","net.minecraft.world.entity.projectile.ShulkerBullet","net.minecraft.world.entity.projectile.hurtingprojectile.AbstractHurtingProjectile","net.minecraft.world.entity.raid.Raider","net.minecraft.world.entity.vehicle.VehicleEntity","net.minecraft.world.entity.vehicle.minecart.MinecartTNT"})
public abstract class ClaimDamageMixin {
 @Inject(method="hurtServer",at=@At("HEAD"),cancellable=true)
 private void claims$damage(ServerLevel level,net.minecraft.world.damagesource.DamageSource source,float amount,CallbackInfoReturnable<Boolean> cir){if(!Claims.damage(source,(net.minecraft.world.entity.Entity)(Object)this))cir.setReturnValue(false);}
}
