import os
SP = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("SB_MODS_ROOT") or str(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(SP)))))  # parent folder that holds all mod repos
rd = lambda n: open(os.path.join(SP, n), encoding="utf-8").read()
pre, contract, port = rd("pre.md"), rd("mm-contract.md"), rd("port.md")

QUALITY = """
OWNER QUALITY BAR (applies to every module, verbatim intent from the owner, translated):
- Every mod must follow the big example SimpleBuilding: good UI and UX (screens, tooltips, sounds/particles/block states instead of on-screen text for gadgets, row layouts in creative tabs, JEI/Jade/wiki/advancement hints, config screen with tabs, defaults stated in every tooltip), and clean code like SimpleBuilding.
- Every mod offers ALL sensible config options, all of them server-authoritative (the client never decides gameplay values), each with a hard cap that Vanilla balance cannot be broken by, none exploitable (think about duplication, infinite loops, buy/sell arbitrage, speed/reach amplification, chunk/entity spam, world-border or claim bypass, griefing in multiplayer; add a config switch and a test for each risk you identify).
- Strict anti-cheat thinking: anything a client can send (packets, key states, movement claims, selected models) is validated and clamped on the server with explicit maximums (for example maximum speed amplification); write tests that send out-of-range values and prove they are clamped or refused.
- Comprehensive tests, all passing: server gametests per feature, config tests (every option has name/tooltip/tab/default-in-tooltip, bounds are enforced), lang completeness (en_us + de_de), data integrity, security/bounds tests, integration tests with simplebuilding, a launch smoke test; run the client smoke where feasible. Do not finish with red or skipped tests.
"""

EXTRA = {
"visuals": """OWNER ADDITIONS FOR THIS MOD: besides porting the existing features, add a set of additional VANILLA-particle effects for more immersion (ambient and reactive: for example footsteps/dust, breath in cold biomes, fireflies or pollen, sparks near fire/lava, water ripples and droplets, leaf/petal fall, magic hints around enchanted items and beacons, damage/healing feedback, etc. - choose tasteful ones; vanilla particle types only, no new particle textures unless essential). Every effect belongs to a category and has INTENSITY LEVELS from off through subtle, normal, strong to maximum (name the levels in the UI and lang: Off, Subtle, Normal, Strong, Maximum); a global level plus per-effect overrides; hard caps on particle counts per tick and per player so even Maximum never lags or floods (client only, performance-safe, respect the vanilla particle setting). Keep the effect ids stable and in ONE registry that the new module simplesounds can mirror (docs/modules/simplevisuals.md must list them).""",
"sounds": """NEW MOD (no source repo): create the module `simplesounds` ("Simple Sounds") with `python tools/newmod.py simplesounds "Simple Sounds"`. Purpose: sound effects that are the counterpart of the visual effects of Simple Visuals, for more immersion: one sound effect per visual effect id (read docs/modules/simplevisuals.md / the simplevisuals module registry once it exists; if simplevisuals is not yet merged, define the effect-id registry in this module's docs and keep the mapping data-driven so it can be aligned later). Same INTENSITY LEVELS as the visuals (Off, Subtle, Normal, Strong, Maximum) with a global level and per-effect overrides, hard volume caps and per-tick/per-player sound-count caps (no spam), client-side only where possible. Prefer existing Vanilla sound events, with pitch/volume variation and layering, over shipping audio files; if you want original sounds generate small royalty-free .ogg files yourself with a script (document the script and keep files tiny, sounds.json entries, subtitles in en_us and de_de). Soft dependency on simplevisuals (optional: follow its level). Wiki/manual, balance data, tests (registry completeness: every visual effect id has a sound mapping or a documented exclusion; level->volume mapping and caps; config bounds).""",
"fun": """OWNER ADDITIONS FOR THIS MOD: after porting, add several more FUN mechanics that do not disturb or change normal gameplay much, similar in spirit to the existing ones (small harmless delights: look at the existing features and design 6-10 new ones; each with config switch, caps, sounds/particles instead of text, wiki entry, tests). Also add PIG, COW, CHICKEN and SHEEP heads, obtainable only via the charged-creeper mechanic (like the mob heads in SimpleBuilding: study SimpleBuilding's mob-head implementation - TweaksItems/HeadAbilities/charged creeper drop logic and its vanilla-texture rendering - and reuse the pattern and helper code through the framework or a copy without creating a dependency between module internals), each with a secret, harmless ability like the other heads, vanilla mob textures, item/ground/wall/worn rendering, creative tab row, JEI/wiki/loot-condition documentation, tests. Then more witty things of your choice (propose them in docs/modules/simplefun.md before implementing; keep gameplay balance intact).""",
"qol": """OWNER ADDITIONS FOR THIS MOD: if further quality-of-life ideas are possible, DO NOT implement them: write them as a list in docs/modules/simplequalityoflife-ideas.md (title, what it does, benefit, risk/exploit potential, effort, overlap with dev mods) for the owner's review. STRICTLY check that the client cannot cheat with any feature (ladder/scaffolding/climb speed, movement tweaks, auto-actions, reach, sorting/transfer actions, packet spam): the server validates everything and every speed/amplification has a hard server-side maximum cap (for example maximum ladder speed multiplier); add tests that send out-of-range values and prove they are clamped.""",
"riding": """OWNER ADDITIONS FOR THIS MOD: if Nautilus (the 26.x rideable nautilus mob) support is not yet implemented in the ported module, implement it too (riding features, armor interplay with SimpleBuilding's nautilus armor). STRICTLY check that the client cannot cheat with any riding feature (speed, leaping, tailwind, steering, dismount tricks): the server validates and every speed amplification has a hard server-side maximum cap; add tests with out-of-range client values proving they are clamped or refused. NOTE: this mod is already ported on branch codex-port-riding / master-to-be - work on top of master once it contains the module.""",
"tweaks": """OWNER ADDITIONS FOR THIS MOD: check this mod THOROUGHLY: a full audit of every feature of the source mod against what SimpleBuilding already ships and what remains; every remaining feature must work, be exploit-safe (server authority, caps), be configurable, documented and tested; also re-verify the already-ported parts inside SimpleBuilding for regressions against the source behavior (list differences in docs/modules/simpletweaks.md with a decision for each).""",
"dimensions": """OWNER VISION FOR THIS MOD (translated): implement it cleanly as a CONFIGURABLE mod for various custom dimensions. The game experience must be very good and never feel weird: everything is always comprehensible or mysterious, never pointless or illogical. The configs must be clean and relatively simple. Read the source READMEs and the `instructions+` folder in the older source directory carefully (they contain the owner's own instructions): follow them. Deliver first a design document docs/modules/simpledimensions.md (dimension catalogue with theme, access/portal logic, rules, rewards, mood, why it makes sense in the world), then implement: data-driven dimension definitions (datapack + config), portals/access with clear in-world logic, per-dimension rules, safe return paths (no player can get stuck; cheat-proof, exploit-safe), compatibility with world upgrade/DataFixer, clean config screen (few clear options with sensible defaults). Include world-generation tests where feasible (dimension registers, portal links, return path, rules applied, config bounds).""",
"models": """OWNER VISION FOR THIS MOD (translated): it should work the way the owner wanted and started (see the skeleton in the source folder, its sources, todo/readme if any): custom MODELS can be stored in a folder and ASSIGNED TO ITEMS WITH THE HELP OF AN ANVIL (the player puts the item in the anvil and picks/assigns a model; build this on the 26.x `item_model` item component where possible, server validates the assignment), and there is a BROWSER (a screen) in which these models can be SEARCHED and ADDED (folder scan, preview in the GUI with 3D item rendering like SimpleBuilding's preview screens, search, tags/categories, add/remove/refresh without restarting, import instructions). Design carefully for multiplayer: who may assign (permission/config), server-side validation of model ids, limits, no way to disguise items for scams if the server disables it (config), resource delivery (models live in a folder on the client/server: decide and document how a server distributes them, e.g. a server resource pack hook or client-local only) and security (path traversal, oversized files, invalid JSON must never crash). UI/UX like SimpleBuilding screens.""",
}

MODS = {
    "qol": ("simplequalityoflife", "Simple Quality of Life", "simplequalityoflife",
            "Multiloader (common/fabric/neoforge) with a legacy-src folder, Minecraft 1.21.11, about 72 Java files, version 1.0.6. Has server config sync (furnace lava-fill etc.). Check carefully for overlaps with SimpleBuilding and with the QoL dev mods listed in tools/devmods.json."),
    "visuals": ("simplevisuals", "Simple Visuals", "simplevisuals",
                "Fabric-only, Minecraft 1.21.11, about 35 Java files, version 1.0.7, client-heavy (tooltips, visuals). Keep client code in client-only classes; add client smoke checks carefully."),
    "dimensions": ("simpledimensions", "Simple Dimensions", "simpledimentions_05-2026",
                   "TWO source folders exist: simpledimentions_05-2026 (Minecraft 26.1.2, common/fabric/forge/neoforge, mod_id simpledimension, newest, PRIMARY) and simpledimensions (older, has paper/ and instructions+ folders with the owner's instructions; path: " + ROOT + "/simpledimensions). Compare both, document the decision. Module id simpledimensions (plural); keep the source registry namespace if worlds depend on it and document it."),
    "models": ("simplemodels", "Simple Models", "renamed",
               "The source folder is called `renamed` (mod id renamed, Minecraft 1.21.11, Fabric, about 8 Java files, single initial commit). The owner wants it named Simple Models (module id simplemodels)."),
    "tweaks": ("simpletweaks", "Simple Tweaks", "simpletweaks",
               "Fabric, Minecraft 1.21.11, about 56 Java files, version 1.2.12, has libs/. Most features were ALREADY ported into SimpleBuilding (see docs/SIMPLETWEAKS-UEBERNAHME.md). In the source repo a local branch `remove-ported-features` may exist (read it with git show, never check it out inside the source repo). The module simpletweaks = ONLY what is NOT ported (claims were deliberately NOT ported; report as a question). A world with both SimpleBuilding and the module must never get duplicate registry entries."),
    "fun": ("simplefun", "Simple Fun", "simplefun",
            "Multiloader (common/fabric/neoforge, buildSrc), Minecraft 1.21.11, about 188 Java files: the biggest one. Split the work into clear stages and commit after each working stage (inventory, registry/content, gameplay, client, new features, tests)."),
}
for key, (mid, disp, src, note) in MODS.items():
    spec = f"- module id: {mid}\n- display name: {disp}\n- source repo (read-only): {ROOT}/{src}\n- notes: {note}\n\n" + EXTRA[key] + "\n"
    open(os.path.join(SP, f"brief-port-{key}.md"), "w", encoding="utf-8").write(pre + "\n" + contract + "\n" + port + QUALITY + "\nMOD TO PORT:\n" + spec)

# new mod: sounds (scaffold, no source)
newmod = ("TASK NEW MODULE (no source repo). Read docs/MULTIMOD.md. Build the module to the same standards as the ports: inventory not needed; scaffold with tools/newmod.py; tests incl. launch smoke and integration with simplebuilding; wiki/manual.json in English and German; balance data per the contract; Launch Hub wiring via the manifest; docs/modules/<id>.md; docs/HANDOFF.md; commit on your branch, no push/merge. Work token-efficiently.\n" + QUALITY + "\nMODULE:\n- module id: simplesounds\n- display name: Simple Sounds\n" + EXTRA["sounds"] + "\n")
open(os.path.join(SP, "brief-new-sounds.md"), "w", encoding="utf-8").write(pre + "\n" + contract + "\n" + newmod)

# follow-up: simple money links into other mods (run after the other modules exist)
money = ("TASK MONEY-LINKS (owner request, translated): connect Simple Money with the other mods as an ADDON. When Simple Money is installed, additional trades become available for items of the other mods (simplebuilding and every module that is present), priced in Simple Money according to the balancing - that means the cost of each other item is entered according to its money value; the old (non-money) trades are NOT removed. Design: data-driven price lists per module (for example modules/<id>/money/prices.json: item id, buy price, optional sell price, stock/level rules, villager profession or merchant, conditions), read by simplemoney only for mods that are loaded (conditional, soft dependency, no hard dependency between modules: use public registry ids), generated through the trade system (data-driven trades since 26.1, see memory note in AGENTS.md / docs: TradeOfferHelper is gone, trades are data; tags merge). Derive prices from the existing balancing (loot rarity, crafting cost, age-of-game model in tools/devserver/sbdev/model.py and docs/KERNE-SELTENHEIT.md, the Balancing-Zentrale): document the price formula, expose the formula parameters as config/balance values (Balancing-Zentrale per module), cap prices and quantities, forbid arbitrage loops (sell price always below buy price, cooldowns, per-day limits) and test for exploits (buy/sell loop never profits). Cover all modules that exist at that time (simplebuilding items like cores, pads, chests, bundles, heads are covered at least by rarity tier), keep mod-id conditions so a missing mod simply adds no offers. Tests: offers exist only when the mod is loaded, old trades remain, price monotonicity vs rarity tiers, no arbitrage, config bounds, lang/wiki/JEI info. The wiki page of Simple Money lists the linked price tables.\n" + QUALITY)
open(os.path.join(SP, "brief-money-links.md"), "w", encoding="utf-8").write(pre + "\n" + contract + "\n" + money)
print("ok")
