package com.simplebuilding.modules.simplelib;

import com.simplelib.test.LibTests;
import net.fabricmc.fabric.api.gametest.v1.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;

/** Fabric adapter: ids module_game_test_<name>, bodies in {@link LibTests}. Generated by the crucible plan helper; keep in sync with LibTests.ALL. */
public final class ModuleGameTest {
    @GameTest
    public void configBounds(GameTestHelper h) {
        LibTests.ALL.get("config_bounds").accept(h);
    }

    @GameTest
    public void tierLayout(GameTestHelper h) {
        LibTests.ALL.get("tier_layout").accept(h);
    }

    @GameTest
    public void heatSources(GameTestHelper h) {
        LibTests.ALL.get("heat_sources").accept(h);
    }

    @GameTest
    public void heatTwoBelow(GameTestHelper h) {
        LibTests.ALL.get("heat_two_below").accept(h);
    }

    @GameTest
    public void cooksIntoSlotBelow(GameTestHelper h) {
        LibTests.ALL.get("cooks_into_slot_below").accept(h);
    }

    @GameTest
    public void mediumHeatBlocksSmelting(GameTestHelper h) {
        LibTests.ALL.get("medium_heat_blocks_smelting").accept(h);
    }

    @GameTest
    public void reservedSlotBlocksAndKeepsProgress(GameTestHelper h) {
        LibTests.ALL.get("reserved_slot_blocks_and_keeps_progress").accept(h);
    }

    @GameTest
    public void resultNotRecooked(GameTestHelper h) {
        LibTests.ALL.get("result_not_recooked").accept(h);
    }

    @GameTest
    public void warmsFoodAndEatsFaster(GameTestHelper h) {
        LibTests.ALL.get("warms_food_and_eats_faster").accept(h);
    }

    @GameTest
    public void afterglowKeepsHeat(GameTestHelper h) {
        LibTests.ALL.get("afterglow_keeps_heat").accept(h);
    }

    @GameTest
    public void hopperRules(GameTestHelper h) {
        LibTests.ALL.get("hopper_rules").accept(h);
    }

    @GameTest
    public void axeBuildsIronCrucible(GameTestHelper h) {
        LibTests.ALL.get("axe_builds_iron_crucible").accept(h);
    }

    @GameTest
    public void breakDropsContents(GameTestHelper h) {
        LibTests.ALL.get("break_drops_contents").accept(h);
    }

    @GameTest
    public void axeUpgradeKeepsContents(GameTestHelper h) {
        LibTests.ALL.get("axe_upgrade_keeps_contents").accept(h);
    }

    @GameTest
    public void warmStacksByMean(GameTestHelper h) {
        LibTests.ALL.get("warm_stacks_by_mean").accept(h);
    }

    @GameTest
    public void warmBundleInsulates(GameTestHelper h) {
        LibTests.ALL.get("warm_bundle_insulates").accept(h);
    }

    @GameTest
    public void villageKitchenInPools(GameTestHelper h) {
        LibTests.ALL.get("village_kitchen_in_pools").accept(h);
    }

    @GameTest
    public void barrelAttachAndResultsFirst(GameTestHelper h) {
        LibTests.ALL.get("barrel_attach_and_results_first").accept(h);
    }

    @GameTest
    public void barrelAttachedLaterTakesOverReservations(GameTestHelper h) {
        LibTests.ALL.get("barrel_attached_later_takes_over_reservations").accept(h);
    }

    @GameTest
    public void clientMenuShowsTheRaisedStackLimit(GameTestHelper h) {
        LibTests.ALL.get("client_menu_shows_the_raised_stack_limit").accept(h);
    }

    @GameTest
    public void axeClickReachesAxeNotMenu(GameTestHelper h) {
        LibTests.ALL.get("axe_click_reaches_axe_not_menu").accept(h);
    }

    @GameTest
    public void axeUpgradesCauldron(GameTestHelper h) {
        LibTests.ALL.get("axe_upgrades_cauldron").accept(h);
    }

    @GameTest
    public void reinforcedCauldronHoldsBuckets(GameTestHelper h) {
        LibTests.ALL.get("reinforced_cauldron_holds_buckets").accept(h);
    }

    @GameTest
    public void reinforcedCauldronInheritsVanilla(GameTestHelper h) {
        LibTests.ALL.get("reinforced_cauldron_inherits_vanilla").accept(h);
    }

    @GameTest
    public void axeUpgradesBarrelToNetherite(GameTestHelper h) {
        LibTests.ALL.get("axe_upgrades_barrel_to_netherite").accept(h);
    }
}
