modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simplesounds"
version="${version}"
displayName="Simple Sounds"
[[dependencies.simplesounds]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"

[[mixins]]
config="simplesounds.mixins.json"
[[dependencies.simplesounds]]
modId="cloth_config"
type="required"
versionRange="[26.3,)"
