package com.simplebuilding.modules.simplesounds;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
public final class SoundTests {
 private static void require(boolean b,String s){if(!b)throw new AssertionError(s);}
 public static void launch(GameTestHelper h){require(SoundsRegistry.ALL.size()==12,"Registry missing");require(!BuiltInRegistries.ITEM.containsKey(Identifier.parse("simplesounds:token")),"Placeholder item leaked");h.succeed();}
 public static void bounds(GameTestHelper h){var c=new SoundConfig();c.globalLevel=null;c.volumeCap=Float.NaN;c.soundsPerTick=Integer.MAX_VALUE;c.soundsPerPlayer=Integer.MAX_VALUE;c.cooldownTicks=Integer.MIN_VALUE;c.overrides.put("unknown",SoundConfig.Level.MAXIMUM);c.overrides.put("cold_breath",null);c.normalize();require(c.globalLevel==SoundConfig.Level.SUBTLE&&c.volumeCap==.25f&&c.soundsPerTick==4&&c.soundsPerPlayer==2&&c.cooldownTicks==20&&c.overrides.isEmpty(),"Unsafe config");c.volumeCap=Float.POSITIVE_INFINITY;c.normalize();require(c.volumeCap==.25f,"Infinity");c.volumeCap=-1;c.soundsPerTick=-1;c.soundsPerPlayer=-1;c.cooldownTicks=Integer.MAX_VALUE;c.normalize();require(c.volumeCap==0&&c.soundsPerTick==0&&c.soundsPerPlayer==0&&c.cooldownTicks==1200,"Lower/upper bounds");h.succeed();}
 public static void flood(GameTestHelper h){var c=new SoundConfig();c.soundsPerTick=999;c.soundsPerPlayer=999;c.cooldownTicks=-1;var b=new SoundBudget();b.begin();int accepted=0;for(int n=0;n<1000;n++)if(b.claim(n%8,SoundsRegistry.ALL.get(n%12).id(),100,c,40))accepted++;require(accepted==4&&b.used()==4,"Tick flood");b.reset();b.begin();accepted=0;for(var e:SoundsRegistry.ALL)if(b.claim(1,e.id(),100,c,40))accepted++;require(accepted==2,"Player flood");b.begin();require(!b.claim(1,"unknown",200,c,20),"Unknown id");h.succeed();}
 public static void cooldown(GameTestHelper h){var c=new SoundConfig();var b=new SoundBudget();require(b.claim(1,"cold_breath",100,c,40),"First sound");b.begin();require(!b.claim(1,"cold_breath",139,c,40),"Early replay");b.begin();require(b.claim(1,"cold_breath",140,c,40),"Cooldown never expires");b.reset();require(b.claim(1,"cold_breath",0,c,40),"World reset");c.soundsPerTick=0;b.begin();require(!b.claim(2,"cold_breath",100,c,40),"Disabled budget");h.succeed();}
 public static void integration(GameTestHelper h){require(BuiltInRegistries.ITEM.containsKey(Identifier.parse("simplebuilding:backpack")),"SimpleBuilding not loaded");var b=new SoundBudget();var c=new SoundConfig();var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);var before=player.getInventory().getItem(0).copy();b.claim(player.getId(),"footstep_dust",100,c,40);require(net.minecraft.world.item.ItemStack.matches(before,player.getInventory().getItem(0)),"Cosmetic budget changes inventory");h.succeed();}
 public static void effect(GameTestHelper h,String id){var e=SoundsRegistry.ALL.stream().filter(v->v.id().equals(id)).findFirst().orElseThrow();require(BuiltInRegistries.SOUND_EVENT.containsKey(Identifier.parse(e.sound())),"Unknown Vanilla sound "+e.sound());var c=new SoundConfig();float previous=-1;for(var l:SoundConfig.Level.values()){c.globalLevel=l;float v=c.volume(e);require(Float.isFinite(v)&&v>=previous&&v<=.25f,"Gain/cap");previous=v;}c.globalLevel=SoundConfig.Level.OFF;require(c.volume(e)==0,"Off");c.overrides.put(id,SoundConfig.Level.MAXIMUM);require(c.volume(e)>0,"Override");c.volumeCap=.01f;require(c.volume(e)<=.01f,"Volume cap");c.overrides.put(id,SoundConfig.Level.OFF);require(c.volume(e)==0,"Override off");h.succeed();}
}
