modLoader="javafml"
loaderVersion="[66,)"
license="CC0-1.0"
[[mods]]
modId="simpledimension"
version="${version}"
displayName="Simple Dimensions"
[[dependencies.simpledimension]]
modId="forge"
mandatory=true
versionRange="[66,)"
ordering="NONE"
side="BOTH"
[[dependencies.simpledimension]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="simplebuilding"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="modmenu"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simpledimension]]
modId="flan"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="ftbchunks"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="openpartiesandclaims"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="griefdefender"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpledimension]]
modId="claimchunk"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
