modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simplemoney"
version="${version}"
displayName="Simple Money"
[[dependencies.simplemoney]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"

[[dependencies.simplemoney]]
modId="cloth_config"
type="required"
versionRange="[26.3,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="simplemoney.links.mixins.json"

[[dependencies.simplemoney]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simplemoney]]
modId="modmenu"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.simplemoney]]
modId="simplebuilding"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplefun"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplemodels"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplequalityoflife"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simpleriding"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplesandwiches"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplesounds"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simpletweaks"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="simplevisuals"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemoney]]
modId="wiringexample"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
