modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simplemodels"
version="${version}"
displayName="Simple Models"
[[dependencies.simplemodels]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"

[[mixins]]
config="simplemodels.mixins.json"
