modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simplemobs"
version="${version}"
displayName="Simple Mobs"
[[dependencies.simplemobs]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"
