# NeoForge fixed profile for MC 26.1.2 line
forge_version_channel=fixed
forge_version_fixed=64.0.9
forge_loader_version_range=[64,)

neoforge_version_channel=fixed
neoforge_version_fixed=26.1.2.75
neoforge_loader_version_range=[11,)

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
