# NeoForge latest-in-line profile for MC 26.1.2 line
forge_version_channel=latest
forge_version_latest=64.+
forge_loader_version_range=[64,)

neoforge_version_channel=latest
neoforge_version_latest=26.+
neoforge_loader_version_range=[11,)

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
