# NeoForge latest-in-line profile for MC 1.21.11 line
forge_version_channel=fixed
forge_version_fixed=0.0.0
forge_loader_version_range=[0,)

neoforge_version_channel=latest
neoforge_version_latest=26.+
neoforge_loader_version_range=[26,)

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
