modLoader="javafml"
loaderVersion="[66,)"
license="CC0-1.0"
[[mods]]
modId="simplevisuals"
version="${version}"
displayName="Simple Visuals"
[[dependencies.simplevisuals]]
modId="forge"
mandatory=true
versionRange="[66,)"
ordering="AFTER"
side="BOTH"
[[dependencies.simplevisuals]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"

[[dependencies.simplevisuals]]
modId="simplebuilding"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplevisuals]]
modId="simplemodels"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplevisuals]]
modId="modmenu"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
