modLoader="javafml"
loaderVersion="[66,)"
license="CC0-1.0"
[[mods]]
modId="__MODID__"
version="${version}"
displayName="__DISPLAY_NAME__"
[[dependencies.__MODID__]]
modId="forge"
mandatory=true
versionRange="[66,)"
ordering="NONE"
side="BOTH"
[[dependencies.__MODID__]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"
