modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="CC0-1.0"

[[mixins]]
config="simplebuilding.mixins.json"

[[mixins]]
config="simplebuilding.client.mixins.json"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="SimpleBuilding"
description='''
SimpleBuilding for NeoForge 26.2
'''
authors="simplebuilding"
displayURL="https://azarfane.de/"
logoFile="assets/simplebuilding/icon.png"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[26,)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="cloth_config"
type="optional"
versionRange="[26,)"
ordering="NONE"
side="BOTH"
