package com.simplevisuals.guide;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.ChatFormatting;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;

/**
 * The Simple Visuals guide - GENERATED by tools/guides/module_guides.py from tools/guides/ClientGuide.java.in, do not edit
 * (plan: docs/ai/PLAN-MODUL-GUIDES-2026-10-05.md).
 *
 * <p>A client-only mod registers no item (that would force it onto the server), so its {@link #PAGES} translatable
 * pages ({@code simplevisuals.guide.page.<n>} and {@code .title}) open in the Vanilla book screen through the local
 * command {@code /simplevisuals guide}. This class holds no client classes, so tests can read the pages anywhere.
 */
public final class VisualsGuide {
    public static final String NAMESPACE = "simplevisuals";
    public static final int PAGES = 43;

    private VisualsGuide() {
    }

    public static Component page(int number) {
        String key = NAMESPACE + ".guide.page." + number;
        return Component.empty().append(Component.translatable(key + ".title").withStyle(ChatFormatting.BOLD))
                .append("\n\n").append(Component.translatable(key));
    }

    public static List<Component> pages() {
        List<Component> pages = new ArrayList<>();
        for (int i = 1; i <= PAGES; i++) {
            pages.add(page(i));
        }
        return pages;
    }

    /** GameTest: the guide has its pages (opening needs a client; the client smoke covers the command). */
    public static void gameTest(GameTestHelper h) {
        h.assertTrue(PAGES > 1 && pages().size() == PAGES, "guide has not " + PAGES + " pages");
        for (String locale : List.of("en_us", "de_de")) {
            String lang = resource("/assets/" + NAMESPACE + "/lang/" + locale + ".json");
            h.assertTrue(lang != null && lang.contains("\"" + NAMESPACE + ".guide.page." + PAGES + ".title\"")
                    && !lang.contains("\"" + NAMESPACE + ".guide.page." + (PAGES + 1) + ".title\""), locale + " lacks the guide pages");
        }
        h.succeed();
    }

    static String resource(String path) {
        try (InputStream in = VisualsGuide.class.getResourceAsStream(path)) {
            return in == null ? null : new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            return null;
        }
    }
}
