package com.simplebuilding.blocks;

import java.util.List;

/**
 * GENERATED by tools/textures/octets_2026_10_09.py from tools/textures/octet_materials.json - do not edit by hand.
 * Every block with stairs and slabs (vanilla and this mod, without planks and chess checkers) gets an octet cell
 * {@code <key>_octet} (Queue N19/N15); {@link ModBlocks#MATERIAL_OCTETS} registers them, in creative-tab order.
 */
public final class OctetMaterials {
    public record Material(String namespace, String base, String key, String group) {
    }

    /** Creative-tab groups in display order. */
    public static final List<String> GROUPS = List.of("stone", "sandstone", "bricks", "deepslate", "tuff", "prismarine", "quartz", "copper", "wool", "concrete", "mod", "other");

    public static final List<Material> ALL = List.of(
            new Material("minecraft", "andesite", "andesite", "stone"),
            new Material("minecraft", "cobblestone", "cobblestone", "stone"),
            new Material("minecraft", "diorite", "diorite", "stone"),
            new Material("minecraft", "granite", "granite", "stone"),
            new Material("minecraft", "mossy_cobblestone", "mossy_cobblestone", "stone"),
            new Material("minecraft", "polished_andesite", "polished_andesite", "stone"),
            new Material("minecraft", "polished_diorite", "polished_diorite", "stone"),
            new Material("minecraft", "polished_granite", "polished_granite", "stone"),
            new Material("minecraft", "stone", "stone", "stone"),
            new Material("minecraft", "red_sandstone", "red_sandstone", "sandstone"),
            new Material("minecraft", "sandstone", "sandstone", "sandstone"),
            new Material("minecraft", "smooth_red_sandstone", "smooth_red_sandstone", "sandstone"),
            new Material("minecraft", "smooth_sandstone", "smooth_sandstone", "sandstone"),
            new Material("minecraft", "bamboo_mosaic", "bamboo_mosaic", "bricks"),
            new Material("minecraft", "bricks", "bricks", "bricks"),
            new Material("minecraft", "cinnabar_bricks", "cinnabar_bricks", "bricks"),
            new Material("minecraft", "end_stone_bricks", "end_stone_bricks", "bricks"),
            new Material("minecraft", "mossy_stone_bricks", "mossy_stone_bricks", "bricks"),
            new Material("minecraft", "mud_bricks", "mud_bricks", "bricks"),
            new Material("minecraft", "nether_bricks", "nether_bricks", "bricks"),
            new Material("minecraft", "red_nether_bricks", "red_nether_bricks", "bricks"),
            new Material("minecraft", "resin_bricks", "resin_bricks", "bricks"),
            new Material("minecraft", "stone_bricks", "stone_bricks", "bricks"),
            new Material("minecraft", "sulfur_bricks", "sulfur_bricks", "bricks"),
            new Material("minecraft", "blackstone", "blackstone_block", "deepslate"),
            new Material("minecraft", "cobbled_deepslate", "cobbled_deepslate", "deepslate"),
            new Material("minecraft", "deepslate_bricks", "deepslate_bricks", "deepslate"),
            new Material("minecraft", "deepslate_tiles", "deepslate_tiles", "deepslate"),
            new Material("minecraft", "polished_blackstone", "polished_blackstone", "deepslate"),
            new Material("minecraft", "polished_blackstone_bricks", "polished_blackstone_bricks", "deepslate"),
            new Material("minecraft", "polished_deepslate", "polished_deepslate", "deepslate"),
            new Material("minecraft", "polished_tuff", "polished_tuff", "tuff"),
            new Material("minecraft", "tuff", "tuff", "tuff"),
            new Material("minecraft", "tuff_bricks", "tuff_bricks", "tuff"),
            new Material("minecraft", "dark_prismarine", "dark_prismarine", "prismarine"),
            new Material("minecraft", "prismarine", "prismarine", "prismarine"),
            new Material("minecraft", "prismarine_bricks", "prismarine_bricks", "prismarine"),
            new Material("minecraft", "purpur_block", "purpur_block", "quartz"),
            new Material("minecraft", "quartz_block", "quartz_block", "quartz"),
            new Material("minecraft", "smooth_quartz", "smooth_quartz", "quartz"),
            new Material("minecraft", "cut_copper", "cut_copper", "copper"),
            new Material("minecraft", "exposed_cut_copper", "exposed_cut_copper", "copper"),
            new Material("minecraft", "weathered_cut_copper", "weathered_cut_copper", "copper"),
            new Material("minecraft", "oxidized_cut_copper", "oxidized_cut_copper", "copper"),
            new Material("minecraft", "waxed_cut_copper", "waxed_cut_copper", "copper"),
            new Material("minecraft", "waxed_exposed_cut_copper", "waxed_exposed_cut_copper", "copper"),
            new Material("minecraft", "waxed_weathered_cut_copper", "waxed_weathered_cut_copper", "copper"),
            new Material("minecraft", "waxed_oxidized_cut_copper", "waxed_oxidized_cut_copper", "copper"),
            new Material("minecraft", "white_wool", "white_wool", "wool"),
            new Material("minecraft", "light_gray_wool", "light_gray_wool", "wool"),
            new Material("minecraft", "gray_wool", "gray_wool", "wool"),
            new Material("minecraft", "black_wool", "black_wool", "wool"),
            new Material("minecraft", "brown_wool", "brown_wool", "wool"),
            new Material("minecraft", "red_wool", "red_wool", "wool"),
            new Material("minecraft", "orange_wool", "orange_wool", "wool"),
            new Material("minecraft", "yellow_wool", "yellow_wool", "wool"),
            new Material("minecraft", "lime_wool", "lime_wool", "wool"),
            new Material("minecraft", "green_wool", "green_wool", "wool"),
            new Material("minecraft", "cyan_wool", "cyan_wool", "wool"),
            new Material("minecraft", "light_blue_wool", "light_blue_wool", "wool"),
            new Material("minecraft", "blue_wool", "blue_wool", "wool"),
            new Material("minecraft", "purple_wool", "purple_wool", "wool"),
            new Material("minecraft", "magenta_wool", "magenta_wool", "wool"),
            new Material("minecraft", "pink_wool", "pink_wool", "wool"),
            new Material("minecraft", "white_concrete", "white_concrete", "concrete"),
            new Material("minecraft", "light_gray_concrete", "light_gray_concrete", "concrete"),
            new Material("minecraft", "gray_concrete", "gray_concrete", "concrete"),
            new Material("minecraft", "black_concrete", "black_concrete", "concrete"),
            new Material("minecraft", "brown_concrete", "brown_concrete", "concrete"),
            new Material("minecraft", "red_concrete", "red_concrete", "concrete"),
            new Material("minecraft", "orange_concrete", "orange_concrete", "concrete"),
            new Material("minecraft", "yellow_concrete", "yellow_concrete", "concrete"),
            new Material("minecraft", "lime_concrete", "lime_concrete", "concrete"),
            new Material("minecraft", "green_concrete", "green_concrete", "concrete"),
            new Material("minecraft", "cyan_concrete", "cyan_concrete", "concrete"),
            new Material("minecraft", "light_blue_concrete", "light_blue_concrete", "concrete"),
            new Material("minecraft", "blue_concrete", "blue_concrete", "concrete"),
            new Material("minecraft", "purple_concrete", "purple_concrete", "concrete"),
            new Material("minecraft", "magenta_concrete", "magenta_concrete", "concrete"),
            new Material("minecraft", "pink_concrete", "pink_concrete", "concrete"),
            new Material("simplebuilding", "astralit_bricks", "astralit_bricks", "mod"),
            new Material("simplebuilding", "ender_quartz_block", "ender_quartz_block", "mod"),
            new Material("simplebuilding", "ender_quartz_bricks", "ender_quartz_bricks", "mod"),
            new Material("simplebuilding", "nihilith_bricks", "nihilith_bricks", "mod"),
            new Material("simplebuilding", "polished_astralit", "polished_astralit_block", "mod"),
            new Material("simplebuilding", "polished_ender_quartz", "polished_ender_quartz_block", "mod"),
            new Material("simplebuilding", "polished_nihilith", "polished_nihilith_block", "mod"),
            new Material("minecraft", "cinnabar", "cinnabar", "other"),
            new Material("minecraft", "polished_cinnabar", "polished_cinnabar", "other"),
            new Material("minecraft", "polished_sulfur", "polished_sulfur", "other"),
            new Material("minecraft", "sulfur", "sulfur", "other"));

    private OctetMaterials() {
    }
}
