modLoader="javafml"
loaderVersion="[66,)"
license="CC0-1.0"
[[mods]]
modId="simpleriding"
version="${version}"
displayName="Simple Riding"
[[dependencies.simpleriding]]
modId="forge"
mandatory=true
versionRange="[66,)"
ordering="AFTER"
side="BOTH"
[[dependencies.simpleriding]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"

[[dependencies.simpleriding]]
modId="simplebuilding"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpleriding]]
modId="modmenu"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
