modLoader="javafml"
loaderVersion="[11,)"
license="CC0-1.0"
[[mods]]
modId="simplevisuals"
version="${version}"
displayName="Simple Visuals"
[[dependencies.simplevisuals]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"
[[dependencies.simplevisuals]]
modId="cloth_config"
type="required"
versionRange="[26.3,)"

[[mixins]]
config="simplevisuals.mixins.json"

[[dependencies.simplevisuals]]
modId="simplebuilding"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplevisuals]]
modId="simplemodels"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplevisuals]]
modId="modmenu"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
